#!/usr/bin/env bash
# Installs and configures a Nginx
# Ngninx x should listen on port 80
# Quering root with GET request (curl) should return  a string "Hello World"

# install Nginx
apt-get update -y
apt-get install -y nginx

# allow firewall access
ufw allow 'Nginx HTTP'

# Create document root directory
mkdir -p /var/www/html/

# create site page to include string "Hello World"
echo "Hello World!" > /var/www/html/index.html


# create server block
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://sketchfab.com/bluepeno/models permanent;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

service nginx start
service nginx restart
# confirm nginx files syntax
nginx -t

# reload nginx config files
nginx -s reload

