#!/usr/bin/env bash
# Installs and configures a Nginx
# Ngninx x should listen on port 80
# Quering root with GET request (curl) should return  a string "Hello World"

# install Nginx
apt-get -y update
apt-get -y install nginx

# allow firewall access
ufw allow 'Nginx HTTP'

# Create document root directory
mkdir -p /var/www/html/

# create site page to include string "Hello World"
echo "Hello World!" > /var/www/html/index.html


# create server block
echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;


        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name ajwadg.tech;

        location /redirect_me {
                return 301 https://www.nginx.com/blog/creating-nginx-rewrite-rules/;
        }
}" | tee /etc/nginx/sites-available/default


service nginx restart
