#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo 'redirection page' > /var/www/html/redirect_me
rm -rf /etc/nginx/sites-available/*
cat <<EOF >/etc/nginx/sites-available/default
	server {
		listen 80 default_server;
		listen [::]:80 default_server;

		root /var/www/html;
		index index.nginx-debian.html;

		server_name _;

		location / {
			try_files \$uri \$uri/ \=404;
		}
		
		rewrite \^/redirect_me\i$ /index.nginx-debian.html permanent;
	}
EOF
rm /etc/nginx/sites-enabled/*
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx start
