#!/usr/bin/env bash
# Installs and configures a Nginx
# Ngninx should listen on port 80

# install Nginx
apt-get -y update
apt-get -y install nginx

# allow firewall access
ufw allow 'Nginx HTTP'

# Create document root directory
mkdir -p /var/www/html/

# create site page to include string "Hello World"
echo "Hello World!" > /var/www/html/index.html


# create server block
cat <<EOF >/etc/nginx/sites-available/default
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name chefzeek.tech;
		
		location / {
			try_files \$uri \$uri/ /xyz;
		} 

        location /xyz {
           return 404 "Ceci n'est pas une page";
        }
    }
EOF
service nginx restart
