#!/usr/bin/env bash
# Installs and configures a Nginx
# Ngninx x should listen on port 80
# Quering root with GET request (curl) should return  a string "Hello World"

# install Nginx
echo 'updating apt-get...'
sudo apt-get update
#apt-get intsall nginx

# allow firewall access
#ufw allow 'HTTP'

# Create document root directory
echo 'Creating root document directory...'
sudo mkdir -p /var/www/chefzeek.tech/html/

# Give user permissions
echo 'Giving user permissions...'
sudo chown -R $USER:$USER /var/www/chefzeek.tech/html/

# create site page to include string "Hello World"
echo 'Creating root page and shouting Hello World!...'
sudo echo "<p>Hello World</p>" > /var/www/chefzeek.tech/html/index.html


# create server block
echo 'Creating and configuring server_block...'
sudo cat <<EOF >/etc/nginx/sites-available/server_block
    server {
        listen 80;
        listen [::]:80;

        root /var/www/chefzeek.tech/html;
        index index.html;

        server_name chefzeek.tech www.chefzeek.tech;

        location / {
            try_files $uri $uri/ \=404;
        }
    }
EOF

# enable server_block by linking with sites-enabled
echo 'enabling server block by linking...'
sudo ln -s /etc/nginx/sites-available/server_block /etc/nginx/sites-enabled/


# open nginx configuration file && uncoment HashBucket line 
#sudo sed -i -E 's/\s*\#\s*(server_names_hash.*$)/\1/' /etc/nginx/nginx.conf

# confirm nginx files syntax
echo 'confirming nginx files...'
sudo nginx -t
