#!/usr/bin/env bash
# Installs and configures a Nginx
# Ngninx x should listen on port 80
# Quering root with GET request (curl) should return  a string "Hello World"

# install Nginx
echo 'updating apt-get...'
apt-get -y update
apt-get -y intsall nginx

# allow firewall access
ufw allow 'HTTP'

# Create document root directory
echo 'Creating root document directory...'
mkdir -p /var/www/chefzeek.tech/html/

# Give user permissions
echo 'Giving user permissions...'
chown -R $USER:$USER /var/www/chefzeek.tech/html/

# create site page to include string "Hello World"
echo 'Creating root page and shouting Hello World!...'
echo "<p>Hello World</p>" > /var/www/chefzeek.tech/html/index.html


# create server block
echo 'Creating and configuring server_block...'
 cat <<EOF >/etc/nginx/sites-available/chefzeek_server
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/chefzeek.tech/html;
        index index.html;

        server_name chefzeek.tech www.chefzeek.tech;

        location / {
            try_files \$uri \$uri/ \=xyz;
            }
        location ~ ^/redirect_me/? {
            return 301 /index.html;
        }
        location /xyz {
            return 404 "Ceci n'est pas une page";
        }
    }
EOF

# enable server_block by linking with sites-enabled
echo 'enabling server block by linking...'
ln -s /etc/nginx/sites-available/chefzeek_server /etc/nginx/sites-enabled/


# open nginx configuration file && uncoment HashBucket line 
#sudo sed -i -E 's/\s*\#\s*(server_names_hash.*$)/\1/' /etc/nginx/nginx.conf

# restarting nginx
service nginx restart

# confirm nginx files syntax
echo 'confirming nginx files...'
sudo nginx -t

# reload nginx configuration files
sudo nginx -s reload
