#!/usr/bin/env bash
# installs nginx and configures it on a remote server
# adds custom header to identify responding servers

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start


cat <<EOF >/etc/nginx/sites-available/default
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name chefzeek.tech;
		add_header X-Served-By "$hostname"; # shellcheck disable=SC2059

        location /redirect_me {
            return 301 https://www.google.com;
        }
    }
EOF
