#!/usr/bin/env bash
# shellcheck disable=SC2154
# installs nginx and configures it on a remote server
# adds custom header to identify responding servers

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start

cat <<EOF >/etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name chefzeek.tech;
        add_header X-Served-By \$hostname;

        location /redirect_me {
            return 301 https://www.google.com;
        }
        location / {
            try_files \$uri \$uri/ /xyz;
                } 

        location /xyz {
            return 404 "Ceci n'est pas une page";
        }
    }
EOF
