#!/usr/bin/env bash
# install and configure haproxy

apt-get -y update
apt-get -y install haproxy=2.0\*


cat << EOF > /etc/haproxy/haproxy.cfg 
global
        log /dev/log local0

defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend web
        bind *:80
        default_backend webservers

backend webservers
        balance roundrobin
        server 37125-web-01 34.224.83.117:80 check
        server 37125-web-02 54.197.90.139:80 check
EOF

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy start
sudo service haproxy restart
