#!/usr/bin/env bash
# install and configure haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

cat << EOF > /etc/haproxy/haproxy.cfg
global
        log /dev/log local0
    
defaults
        log global
        mode http
        option httplog
        option dontlognull
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend web
        bind *:80
        default_backend webservers

backend webservers
        balance roundrobin
        server 37125-web-01 34.224.83.117:80 check
        server 37125-web-02 54.197.90.139:80 check
EOF

haproxy -c -f /etc/haproxy/haproxy.cfg
ervice haproxy start
