#!/usr/bin/env bash
# Checks availability of network devices

ip_address=$1
script_name=$(basename "$0")

# Check if an IP address is provided
if [ -z "$ip_address" ]; then
    echo "Usage: $script_name (IP_ADDRESS)"
    exit 1
fi

ping -c 5 "$ip_address"
