#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.

# Requirements:

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/host ~/hosts.new
sed -i "s/^127\.[0-9\.]\+/127.0.0.2/" ~/hosts.new
sed -i "s/^157\.[0-9\.]\+/8.8.8.8/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
