#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.

# Requirements:

# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/host ~/hosts.new
sed -i 's/^127.*localhost(\s*)?/127.0.0.2 localhost/' ~/hosts.new
sed -i '/facebook.com/ s/.*/8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
